### ISSUE TITLE
Possible issue with Inovelli switch

### ISSUE THREAD

**Issue by kevinkahn** [OpenZWave/qt-openzwave#51] opened 2020-03-03 05:39 UTC
I have mostly Homeseer switches and these are working ok. However, I have a single Inovelli switch and it is not. When I turn on the switch from HA it sends a setvalue command just as it does for the Homeseer units. I looked at the value id and it corresponds to the command class 37 value that was read from the Invelli switch during startup. So the correspondence looks correct and it is trying to set the value to true (which would be on). However, unlike the Homeseer units which get an immediate response with the new state as on, there is no response from the Inovelli unit. This worked ok under the old zwave stuff. It appears that somewhere in OpenZWave or the OZW mqtt adapter, things are getting lost.  Not sure if this is the right place to put this issue (point me to a better spot if it isn't) but it looks like the HA side is issuing a reasonable mqtt command.

**Comment by erikced** [comment] 2020-03-03 06:48
I see the something similar with my 3 qubino flush dimmers (they change but status in HA is never updated), whereas my fibaro dimmer 2 works as expected.

**Comment by Fishwaldo** [comment] 2020-03-03 07:13
Logs?

**Comment by kevinkahn** [comment] 2020-03-03 18:47
Here are the log from OZW and the output of a mosquitto_sub filtered for OpenZWave topic items.  There are 2 nodes of interest.  Node 6 is a Homeseer switch.  I issued an on and and off for it and you will see in the mqtt stream the setvalues for valueid 105463824 for setting true and false.  In each case that is followed by a state report for the switch in the new state.  The other node is 23 and this is the Inovelli switch.  For it the relevant setvalue valueid is 390676496 which appears in the mqtt stream.  However, for it no state report follows but there is a timeout message.  Let me know if you need something else. 
[logs.zip](https://github.com/OpenZWave/qt-openzwave/files/4283011/logs.zip)

**Comment by Fishwaldo** [comment] 2020-03-04 02:57
Looking at the logs, for whatever reason, the switch refuses to respond to a SwitchBinary_Get message which is perfectly valid from a protocol perspective. 

So seems the problem is with the device itself. I suggest you raise the issue with Inovelli and see what they say. 

(moving to OZW repository and closing for now. If they come back with something additional, please reopen)

@erikced please raise a separate issue

**Closed by Fishwaldo** 2020-03-04 02:57 UTC
